{
 "title": "Domain Exporter",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Last Check",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "domain_check_timestamp_seconds * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Checks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "domain_check_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Status: Unknown",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(domain_status == 0) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status: Free / Pending Delete",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(domain_status == 1 or domain_status == 2) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 4 },
   "targets": [
    { "expr": "domain_status", "legendFormat": "__auto" },
    { "expr": "domain_probe_method", "legendFormat": "__auto" },
    { "expr": "domain_probe_duration_seconds", "legendFormat": "__auto" },
    { "expr": "domain_expires_at * 1000", "legendFormat": "__auto" }
   ]
  }
 ]
}